import { useEffect, useMemo, useRef, useState } from 'react'
import {
  Activity, ArrowLeft, BarChart3, BookOpen, CheckCircle2, ChevronRight, Clock3, Code2,
  Database, FileCheck2, LayoutDashboard, Menu, MessageCircle, Play, Save, Search, ShieldCheck,
  Sparkles, UserRound, X, LogOut, Mail, Chrome, RefreshCw, ExternalLink
} from 'lucide-react'
import { api } from './services/api'
import { firebaseConfigured, googleSignIn, emailSignIn, emailSignUp, logout as firebaseLogout } from './services/firebase'

const fallbackProfile = { name:'', degree:'', college:'', email:'', linkedin:'', github:'', about:'' }

export default function App(){
  const [page,setPage]=useState('dashboard'); const [history,setHistory]=useState([]); const [mobileOpen,setMobileOpen]=useState(false)
  const [profile,setProfile]=useState(fallbackProfile); const [tasks,setTasks]=useState([]); const [evidence,setEvidence]=useState([])
  const [session,setSession]=useState(null); const [authUser,setAuthUser]=useState(()=>JSON.parse(localStorage.getItem('skillproof_auth_user')||'null'))
  const [authMode,setAuthMode]=useState('signin'); const [toast,setToast]=useState(''); const [loading,setLoading]=useState(true)
  const notify=msg=>{setToast(msg);setTimeout(()=>setToast(''),3000)}
  const refresh=async()=>{try{const [p,t,e]=await Promise.all([api.profile(),api.tasks(),api.evidence()]);setProfile(p||fallbackProfile);setTasks(t||[]);setEvidence(e||[])}catch(e){notify('Backend not connected. Start FastAPI on port 8000.')}finally{setLoading(false)}}
  useEffect(()=>{
    if(!authUser){ setLoading(false); return }
    setLoading(true)
    refresh()
    const id=localStorage.getItem('skillproof_session')
    const restore=s=>{ if(s){ setSession(s); localStorage.setItem('skillproof_session',String(s.id)) } }
    if(id) api.session(id).then(restore).catch(()=>{ localStorage.removeItem('skillproof_session'); api.resume().then(restore).catch(()=>{}) })
    else api.resume().then(restore).catch(()=>{})
  },[authUser?.uid])
  const nav=[['dashboard','Dashboard',LayoutDashboard],['tasks','Tasks',BookOpen],['workroom','Workroom',Code2],['proof','My Proof',ShieldCheck],['skills','Skills',BarChart3],['activity','Activity',Activity]]
  const go=(id,push=true)=>{if(push&&id!==page)setHistory(h=>[...h,page]);setPage(id);setMobileOpen(false)}
  const back=()=>setHistory(h=>{if(!h.length)return h;const n=[...h];setPage(n.pop()||'dashboard');return n})
  const register=async(data)=>{const p=await api.register(data);setProfile(p);localStorage.setItem('skillproof_profile_complete','true');go('dashboard',false);notify('SkillProof profile created')}
  const startTask=async task=>{try{const s=await api.startSession(task.id);setSession(s);localStorage.setItem('skillproof_session',String(s.id));go('workroom')}catch(e){notify(e.message)}}
  const onAuth=async (user, providedName='')=>{const u={uid:user.uid,email:user.email||'',name:providedName||user.displayName||''};setAuthUser(u);localStorage.setItem('skillproof_auth_user',JSON.stringify(u));notify('Signed in successfully')}
  const signOut=async()=>{try{await firebaseLogout()}catch{} localStorage.removeItem('skillproof_auth_user');localStorage.removeItem('skillproof_profile_complete');setAuthUser(null);setSession(null);setPage('dashboard');notify('Signed out')}
  if(loading)return <div className="loading"><div><div className="brand registration-brand"><div className="brand-mark">S</div><div><strong>SkillProof</strong><span>Proof over claims</span></div></div><p>Loading your workspace…</p></div></div>
  if(!authUser)return <AuthScreen mode={authMode} setMode={setAuthMode} onAuth={onAuth} notify={notify}/>
  const profileReady=Boolean(profile?.registered)
  if(!profileReady)return <Registration authUser={authUser} onRegister={register}/>
  return <div className="app">
    <aside className={`sidebar ${mobileOpen?'open':''}`}><div className="brand"><div className="brand-mark">S</div><div><strong>SkillProof</strong><span>Proof over claims</span></div></div><div className="nav-label">Workspace</div><nav>{nav.map(([id,label,Icon])=><button key={id} className={`nav-item ${page===id?'active':''}`} onClick={()=>go(id)}><Icon size={18}/><span>{label}</span></button>)}</nav><div className="sidebar-bottom"><button className="nav-item" onClick={()=>go('profile')}><UserRound size={18}/><span>Profile</span></button><button className="nav-item" onClick={signOut}><LogOut size={18}/><span>Sign out</span></button><div className="mini-profile"><div className="avatar">{initials(profile.name)}</div><div><b>{profile.name}</b><small>{profile.degree}</small></div></div></div></aside>
    <main className="main"><header className="topbar"><div className="top-left"><button className="back-btn" onClick={back} disabled={!history.length}><ArrowLeft size={17}/><span>Back</span></button><button className="mobile-menu" onClick={()=>setMobileOpen(v=>!v)}><Menu/></button><div className="crumb">{page==='workroom'?'Workroom':page.replace('-',' ')}</div></div><button className="profile-top" onClick={()=>go('profile')}><div className="avatar">{initials(profile.name)}</div><span>{profile.name}</span></button></header>
      <div className="content">{page==='dashboard'&&<Dashboard profile={profile} tasks={tasks} evidence={evidence} startTask={startTask} go={go}/>} {page==='tasks'&&<Tasks tasks={tasks} startTask={startTask}/>} {page==='workroom'&&<Workroom session={session} setSession={setSession} notify={notify} go={go} refresh={refresh}/>} {page==='proof'&&<Proof profile={profile} evidence={evidence} notify={notify}/>} {page==='skills'&&<Skills evidence={evidence}/>} {page==='activity'&&<ActivityPage evidence={evidence}/>} {page==='profile'&&<Profile profile={profile} setProfile={setProfile} notify={notify}/>}</div>
    </main>{toast&&<div className="toast">{toast}</div>}</div>
}

const initials=n=>(n||'SP').split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase()
function AuthScreen({mode,setMode,onAuth,notify}){const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [name,setName]=useState('');const [busy,setBusy]=useState(false)
 const submit=async e=>{e.preventDefault();setBusy(true);try{const u=mode==='signin'?await emailSignIn(email,password):await emailSignUp(email,password);await onAuth(u,name)}catch(e){notify(e.message)}finally{setBusy(false)}}
 const google=async()=>{setBusy(true);try{await onAuth(await googleSignIn())}catch(e){notify(e.message)}finally{setBusy(false)}}
 return <div className="auth-shell"><div className="auth-card"><div className="brand registration-brand"><div className="brand-mark">S</div><div><strong>SkillProof</strong><span>Proof over claims</span></div></div><div className="eyebrow">{mode==='signin'?'Welcome back':'Create your account'}</div><h1>{mode==='signin'?'Sign in to SkillProof':'Start building your proof.'}</h1><p className="auth-copy">Demonstrate practical skills through real work, guided learning and evidence.</p><button className="google-btn" onClick={google} disabled={busy}><Chrome size={18}/> Continue with Google</button><div className="divider"><span>or continue with email</span></div><form onSubmit={submit} className="auth-form">{mode==='signup'&&<label>Name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Your name" required/></label>}<label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Minimum 6 characters" minLength="6" required/></label><button className="primary full" disabled={busy}>{busy?'Please wait…':mode==='signin'?'Sign in':'Create account'}</button></form><button className="switch-auth" onClick={()=>setMode(mode==='signin'?'signup':'signin')}>{mode==='signin'?"Don't have an account? Sign up":"Already have an account? Sign in"}</button><p className="auth-note">{firebaseConfigured?'Google and email authentication are enabled.':'Demo UI is ready. Add Firebase keys in frontend/.env to enable real Google/email authentication.'}</p></div></div>}

function Registration({authUser,onRegister}){const [form,setForm]=useState({name:authUser.name||'',degree:'',college:'',email:authUser.email||'',linkedin:'',github:'',about:''});const [busy,setBusy]=useState(false);const submit=async e=>{e.preventDefault();setBusy(true);try{await onRegister(form)}finally{setBusy(false)}};return <div className="registration-shell"><div className="registration-card"><div className="brand registration-brand"><div className="brand-mark">S</div><div><strong>SkillProof</strong><span>Proof over claims</span></div></div><div className="eyebrow">Complete your profile</div><h1>Make your proof personal.</h1><p className="registration-intro">Add your academic details so tasks and evidence can be connected to your profile.</p><form className="form-card registration-form" onSubmit={submit}>{[['name','Full name'],['degree','Degree / Course'],['college','College'],['email','Email']].map(([k,l])=><label key={k}>{l}<span className="required">*</span><input required value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label>LinkedIn<input value={form.linkedin} onChange={e=>setForm({...form,linkedin:e.target.value})}/></label><label>GitHub<input value={form.github} onChange={e=>setForm({...form,github:e.target.value})}/></label><label>About<textarea value={form.about} onChange={e=>setForm({...form,about:e.target.value})}/></label><button className="primary register-btn" disabled={busy}>{busy?'Saving…':'Create SkillProof Profile →'}</button></form></div></div>}

function PageTitle({eyebrow,title,text,action}){return <div className="page-title"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1>{text&&<p>{text}</p>}</div>{action}</div>}
function Dashboard({profile,tasks,evidence,startTask,go}){const avg=evidence.length?Math.round(evidence.reduce((a,e)=>a+e.score,0)/evidence.length):0;const skills=new Set(evidence.map(e=>e.skill)).size;return <div><PageTitle eyebrow="Overview" title={`Welcome back, ${profile.name.split(' ')[0]||'student'}.`} text="Build proof by completing practical work, not by collecting claims."/><div className="stats"><Stat label="Skill Progress" value={`${avg}%`} icon={BarChart3}/><Stat label="Skills Demonstrated" value={skills} icon={CheckCircle2}/><Stat label="Tasks Completed" value={evidence.length} icon={FileCheck2}/><Stat label="Proof Profile" value={evidence.length?'Building':'Start'} icon={ShieldCheck}/></div><section className="section"><div className="section-head"><h2>Recommended tasks</h2><button className="link-btn" onClick={()=>go('tasks')}>View all <ChevronRight size={16}/></button></div><div className="task-grid">{tasks.slice(0,3).map(t=><TaskCard key={t.id} task={t} onStart={()=>startTask(t)}/>)}</div></section><section className="section"><div className="section-head"><h2>Recent activity</h2></div><div className="activity-card">{evidence.length?evidence.slice(0,4).map(e=><ActivityRow key={e.id} e={e}/>):<Empty text="Complete your first task to start building evidence."/>}</div></section></div>}
function Stat({label,value,icon:Icon}){return <div className="stat"><div className="icon-box"><Icon size={19}/></div><div><span>{label}</span><strong>{value}</strong></div></div>}
function Tasks({tasks,startTask}){const [q,setQ]=useState('');const [course,setCourse]=useState('All');const [subject,setSubject]=useState('All');const [skill,setSkill]=useState('All');const courses=['All',...new Set(tasks.map(t=>t.course))];const subjects=['All',...new Set(tasks.filter(t=>course==='All'||t.course===course).map(t=>t.subject))];const skills=['All',...new Set(tasks.filter(t=>(course==='All'||t.course===course)&&(subject==='All'||t.subject===subject)).map(t=>t.skill))];const shown=tasks.filter(t=>(course==='All'||t.course===course)&&(subject==='All'||t.subject===subject)&&(skill==='All'||t.skill===skill)&&`${t.title} ${t.skill} ${t.subject} ${t.course}`.toLowerCase().includes(q.toLowerCase()));return <div><PageTitle eyebrow="Task Library" title="Choose a skill to demonstrate." text="Every task routes you to a workspace designed for the discipline."/><div className="filters"><div className="search"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search tasks, skills or subjects…"/></div><select value={course} onChange={e=>{setCourse(e.target.value);setSubject('All');setSkill('All')}}>{courses.map(x=><option key={x}>{x}</option>)}</select><select value={subject} onChange={e=>{setSubject(e.target.value);setSkill('All')}}>{subjects.map(x=><option key={x}>{x}</option>)}</select><select value={skill} onChange={e=>setSkill(e.target.value)}>{skills.map(x=><option key={x}>{x}</option>)}</select></div><div className="task-grid">{shown.map(t=><TaskCard key={t.id} task={t} onStart={()=>startTask(t)}/>)}</div>{!shown.length&&<Empty text="No tasks match your filters."/>}</div>}
function TaskCard({task,onStart}){return <article className="task-card"><div className="task-top"><span className="tag">{task.skill}</span><span className="difficulty">{task.difficulty}</span></div><div className="task-context">{task.course} • {task.subject}</div><h3>{task.title}</h3><p>{task.description}</p><div className="task-meta"><span><Clock3 size={15}/>{task.estimated_minutes} min</span><span><Code2 size={15}/>{prettyWorkspace(task.workspace_type)}</span></div><button className="primary" onClick={onStart}>Start Task <ChevronRight size={16}/></button></article>}

const prettyWorkspace=x=>({python:'Python Coding',java:'Java Coding',coding:'Coding',sql:'SQL Workspace',dashboard:'Dashboard',spreadsheet:'Spreadsheet',accounting:'Accounting',physics:'Physics Lab',lab:'Lab Analysis',math:'Math & Statistics',business:'Business Analysis',writing:'Writing Workspace',design:'Design Studio',general:'General Workspace'}[x]||x)

function Workroom({session,setSession,notify,go,refresh}){const [code,setCode]=useState(session?.current_code||'');const [state,setState]=useState(session?.workspace_state||{});const [output,setOutput]=useState('');const [messages,setMessages]=useState([{role:'ai',text:'Hi! I am SkillGuide. Ask me about a specific step, concept, error or decision. I will guide you without doing the task for you.'}]);const [mentorInput,setMentorInput]=useState('');const [mentorStatus,setMentorStatus]=useState('Ready');const [evaluation,setEvaluation]=useState(session?.evaluation&&Object.keys(session.evaluation).length?session.evaluation:null);const [check,setCheck]=useState(null);const [answers,setAnswers]=useState({});const [busy,setBusy]=useState(false);const saveTimer=useRef(null)
 useEffect(()=>{setCode(session?.current_code||'');setState(session?.workspace_state||{});setEvaluation(session?.evaluation&&Object.keys(session.evaluation).length?session.evaluation:null)},[session?.id])
 useEffect(()=>{if(!session)return;clearTimeout(saveTimer.current);saveTimer.current=setTimeout(()=>api.saveVersion(session.id,code,state,'Auto-save').then(s=>setSession(s)).catch(()=>{}),1400);return()=>clearTimeout(saveTimer.current)},[code,state,session?.id])
 if(!session)return <div className="empty-work"><Code2 size={38}/><h2>No active session</h2><p>Choose a task from the Task Library to enter the Workroom.</p><button className="primary" onClick={()=>go('tasks')}>Browse tasks</button></div>
 const save=async(note='Student saved a version')=>{setBusy(true);try{const s=await api.saveVersion(session.id,code,state,note);setSession(s);notify(note==='Auto-save'?'Work auto-saved':'Version saved')}catch(e){notify(e.message)}finally{setBusy(false)}}
 const run=async()=>{setBusy(true);try{const r=await api.run(session.id,code,state);setOutput(r.output)}catch(e){setOutput(e.message)}finally{setBusy(false)}}
 const ask=async()=>{if(!mentorInput.trim())return;const q=mentorInput;setMentorInput('');const next=[...messages,{role:'user',text:q}];setMessages(next);try{const r=await api.mentor(session.id,q,code,state,next.slice(-8));setMentorStatus(r.ai_connected?'Live AI':'SkillGuide fallback');setMessages(m=>[...m,{role:'ai',text:r.message}])}catch(e){notify(e.message)}}
 const evaluate=async()=>{setBusy(true);try{await save('Submission snapshot');const r=await api.evaluate(session.id);setEvaluation(r);setCheck(null);notify('AI evaluation completed')}catch(e){notify(e.message)}finally{setBusy(false)}}
 const startCheck=()=>{setAnswers({});setCheck(evaluation?.understanding_check||null);setEvaluation(null)}
 const submitCheck=async()=>{try{const r=await api.submitCheck(session.id,answers);setCheck(r);if(r.passed){notify('Understanding verified — SkillProof created');await refresh()}else notify('Add more specific reasoning and try again.')}catch(e){notify(e.message)}}
 const update=(k,v)=>setState(s=>({...s,[k]:v}));
 return <div><div className="work-header"><div><div className="eyebrow">{session.task.course} • {session.task.subject} • {session.task.skill} • {session.task.difficulty}</div><h1>{session.task.title}</h1><div className="work-status"><span className="live-dot"></span>Auto-save on · {prettyWorkspace(session.task.workspace_type)}</div></div><div className="work-actions"><button className="secondary" onClick={()=>save()} disabled={busy}><Save size={16}/> Save</button><button className="primary" onClick={evaluate} disabled={busy}><FileCheck2 size={16}/> {busy?'Evaluating…':'Submit for AI Evaluation'}</button></div></div><div className="work-grid"><aside className="work-panel brief"><h3>Task Brief</h3><div className="scenario">{session.task.scenario}</div><h4>Requirements</h4><ul>{session.task.requirements.map((r,i)=><li key={i}>{r}</li>)}</ul><h4>Resource</h4><div className="resource">{session.task.resource||'No external resource required.'}</div><div className="session-status"><span className="dot"></span>Session active</div></aside><section className="work-panel editor-panel"><Workspace task={session.task} code={code} setCode={setCode} state={state} update={update}/><div className="editor-actions"><button className="secondary" onClick={run} disabled={busy}><Play size={15}/> Run / Preview</button><button className="secondary" onClick={()=>save()}><Save size={15}/> Save Version</button></div><div className="output"><div className="output-title"><span>Output / Preview</span><span>{output?'Updated just now':'Ready'}</span></div><pre>{output||'Run / Preview to see the result of your current work here.'}</pre></div></section><aside className="work-panel mentor"><div className="mentor-head"><div className="ai-icon"><Sparkles size={17}/></div><div><b>SkillGuide</b><small>{mentorStatus}</small></div></div><div className="messages">{messages.map((m,i)=><div key={i} className={m.role==='user'?'msg user':'msg'}>{m.text}</div>)}</div><div className="mentor-note">Task-aware guidance · no ready-made submissions.</div><div className="mentor-input"><input value={mentorInput} onChange={e=>setMentorInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&ask()} placeholder="Ask anything about your work…"/><button onClick={ask}><MessageCircle size={16}/></button></div></aside></div>{evaluation&&<EvaluationModal evaluation={evaluation} onContinue={startCheck} onClose={()=>setEvaluation(null)}/>} {check&&!check.passed&&check.questions&&<UnderstandingModal check={check} answers={answers} setAnswers={setAnswers} onSubmit={submitCheck} onClose={()=>setCheck(null)}/>} {check&&check.passed&&<Modal title="Skill Demonstrated"><div className="success"><CheckCircle2 size={38}/><h2>Evidence created</h2><p>Your work, evaluation and understanding are now part of your SkillProof evidence.</p></div><button className="primary full" onClick={()=>{setCheck(null);go('proof')}}>View My Proof</button></Modal>}</div>}

function Workspace({task,code,setCode,state,update}){const wt=task.workspace_type; if(['python','java','coding','sql'].includes(wt))return <><div className="workspace-title"><b>{prettyWorkspace(wt)}</b><span>Version-aware</span></div><textarea className="code-editor" value={code} onChange={e=>setCode(e.target.value)} spellCheck="false" placeholder="Work on your solution here…"/></>
 const fields={physics:[['observations','Observations','Record measured values and what you observed.'],['calculations','Calculations / reasoning','Show the relationship, units and calculations.'],['graph','Graph / comparison','Describe the graph or comparison you made.'],['conclusion','Conclusion','State what the evidence supports and one limitation.']],lab:[['observations','Observations','Record experimental observations.'],['analysis','Analysis','Interpret the data and identify patterns.'],['conclusion','Conclusion','Connect your conclusion to evidence.']],accounting:[['records','Records / reconciliation','Enter the relevant book and statement items.'],['calculation','Calculation','Show the arithmetic or accounting treatment.'],['reasoning','Investigation / reasoning','Explain why the difference exists.']],spreadsheet:[['table','Table / key values','Record the relevant figures or formulas.'],['findings','Findings','Write the patterns you found.'],['recommendations','Recommendations','Give evidence-based recommendations.']],dashboard:[['kpis','KPIs','List the KPIs you selected and why.'],['visuals','Visual plan','Describe the visuals and filters you used.'],['insights','Insights','Write two evidence-backed insights.']],math:[['problem','Problem setup','Define variables and assumptions.'],['working','Working','Show the calculation or method.'],['interpretation','Interpretation','Explain what the result means.']],business:[['evidence','Evidence','Record the evidence you used.'],['analysis','Business analysis','Explain the pattern or issue.'],['recommendation','Recommendation','Propose a testable next step.']],writing:[['draft','Draft','Write your response or summary.'],['evidence','Evidence check','List the claims that need support.'],['editing','Editing decision','Explain one important editing choice.']],design:[['brief','Design brief','Define audience, goal and constraints.'],['concept','Concept','Describe the visual direction and idea.'],['reasoning','Design reasoning','Explain why your choices fit the brief.']]}[wt]||[['work','Work area','Document your approach and result.']];return <><div className="workspace-title"><b>{prettyWorkspace(wt)}</b><span>Task-specific workspace</span></div><div className="structured-work">{fields.map(([k,l,p])=><label key={k}><span>{l}</span><small>{p}</small><textarea value={state[k]||''} onChange={e=>update(k,e.target.value)} placeholder="Your work…"/></label>)}</div></>}
function EvaluationModal({evaluation,onContinue,onClose}){return <Modal title="AI Evaluation" close={onClose}><div className="score">{evaluation.score}%<span>Demonstration score</span></div><div className="criteria">{Object.entries(evaluation.criteria||{}).map(([k,v])=><div key={k}><span>{k}</span><b>{v}</b></div>)}</div><p className="muted">{evaluation.feedback||'Complete the understanding check before evidence is finalized.'}</p><div className="modal-actions"><button className="secondary" onClick={onClose}>Close</button><button className="primary" onClick={onContinue}>Continue to Understanding Check</button></div></Modal>}
function UnderstandingModal({check,answers,setAnswers,onSubmit,onClose}){return <Modal title="Understanding Check" close={onClose}><p className="muted">Answer these questions using your own submitted work.</p>{check.questions.map((q,i)=><div className="question" key={i}><b>{i+1}. {q.question}</b><textarea value={answers[i]||''} onChange={e=>setAnswers({...answers,[i]:e.target.value})} placeholder="Explain your reasoning…"/></div>)}<div className="modal-actions"><button className="secondary" onClick={onClose}>Later</button><button className="primary" onClick={onSubmit}>Submit Understanding</button></div></Modal>}
function Modal({title,children,close}){return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><h2>{title}</h2>{close&&<button className="icon-btn" onClick={close}><X size={18}/></button>}</div>{children}</div></div>}
function Proof({profile,evidence,notify}){const [selected,setSelected]=useState(null);return <div><PageTitle eyebrow="Evidence" title="My Proof" text="Evidence of demonstrated ability — built from actual work."/><div className="profile-card"><div className="avatar large">{initials(profile.name)}</div><div><h2>{profile.name}</h2><p>{profile.degree} • {profile.college}</p></div><div className="proof-badge"><ShieldCheck size={16}/> Evidence-based</div></div><div className="section"><div className="section-head"><h2>Demonstrated work</h2></div><div className="evidence-grid">{evidence.length?evidence.map(e=><div className="evidence-card" key={e.id}><span className="tag">{e.skill}</span><h3>{e.task_title}</h3><p>{e.capabilities}</p><div className="evidence-foot"><span>{e.score}% demonstrated</span><span>{new Date(e.created_at).toLocaleDateString()}</span></div><button className="secondary full" onClick={()=>setSelected(e)}>View Evaluation</button></div>):<Empty text="No evidence yet. Complete a task to build your proof."/>}</div></div>{selected&&<EvidenceModal evidence={selected} close={()=>setSelected(null)}/>}</div>}
function EvidenceModal({evidence,close}){return <Modal title="Evidence Detail" close={close}><div className="evidence-detail"><div className="detail-score">{evidence.score}%<span>Demonstration</span></div><h3>{evidence.task_title}</h3><p>{evidence.capabilities}</p><div className="criteria">{Object.entries(evidence.evaluation?.criteria||{}).map(([k,v])=><div key={k}><span>{k}</span><b>{v}</b></div>)}</div><h4>Understanding</h4><p>{evidence.understanding?.feedback||'Understanding record available.'}</p></div></Modal>}
function Skills({evidence}){const skills=Array.from(new Set(evidence.map(e=>e.skill)));const avg=s=>Math.round(evidence.filter(e=>e.skill===s).reduce((a,e)=>a+e.score,0)/(evidence.filter(e=>e.skill===s).length||1));return <div><PageTitle eyebrow="Capabilities" title="Skills Demonstrated" text="Progress is derived from evidence, evaluation and completed demonstrations."/><div className="skill-list">{skills.length?skills.map(s=><div className="skill-row" key={s}><div className="skill-icon"><Code2 size={17}/></div><div><b>{s}</b><div className="progress"><span style={{width:`${avg(s)}%`}}/></div><p>{avg(s)}% demonstration progress · {evidence.filter(e=>e.skill===s).length} proof record(s)</p></div><span className="status demonstrated">Demonstrated</span></div>):<Empty text="Complete a practical task to demonstrate your first skill."/>}</div></div>}
function ActivityPage({evidence}){return <div><PageTitle eyebrow="Timeline" title="Activity" text="A transparent history of your work and proof."/><div className="activity-card">{evidence.length?evidence.map(e=><ActivityRow e={e} key={e.id}/>):<Empty text="No activity yet."/>}</div></div>}
function ActivityRow({e}){return <div className="activity-row"><div className="timeline-dot"></div><div><b>{e.task_title}</b><p>{e.skill} demonstrated • {e.score}% evaluation</p></div><span>{new Date(e.created_at).toLocaleDateString()}</span></div>}
function Profile({profile,setProfile,notify}){const [form,setForm]=useState(profile);const save=async()=>{try{const p=await api.updateProfile(form);setProfile(p);notify('Profile updated')}catch(e){notify(e.message)}};return <div><PageTitle eyebrow="Account" title="Edit Profile" text="Keep your SkillProof identity and professional links up to date."/><div className="form-card">{[['name','Full name'],['degree','Degree / Course'],['college','College'],['email','Email'],['linkedin','LinkedIn URL'],['github','GitHub URL']].map(([k,l])=><label key={k}>{l}<input value={form[k]||''} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label>About<textarea value={form.about||''} onChange={e=>setForm({...form,about:e.target.value})}/></label><button className="primary" onClick={save}>Save Profile</button></div></div>}
function Empty({text}){return <div className="empty"><Database size={25}/><p>{text}</p></div>}
